DistrictPlayGroundManagementSystem/Areas/Admin/Controllers/GroundController.cs
using DistrictPlayGroundManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistrictPlayGroundManagementSystem.Areas.Admin.Controllers
{
    [AuthorizeAdmin]
    public class GroundController : Controller
    {
        // GET: Admin/Ground
        public DistrictPlayGroundManagmentEntities dbcontext = new DistrictPlayGroundManagmentEntities();
        
        public ActionResult Index()
        {
            ViewBag.Message = TempData["Message"];
            ViewBag.Error = TempData["Error"];
            var list = dbcontext.Grounds.Where(X => X.IsDeleted == false).ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var GroundType = dbcontext.GroundTypes.Where(x => x.IsDeleted == false).ToList();
            var dropdown = from type in GroundType
                           select new { value = type.id, text = type.GroundType1 };
            ViewBag.GroundType = dropdown;
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(DistrictPlayGroundManagementSystem.Ground ground)
        {
            try
            {
                if (Request.Files.Count > 0)
                {
                    string FilePath = null;
                    var file = Request.Files[0];
                    if (file != null)
                    {
                        string[] SupportedImageFormat = { ".jpeg", ".png", ".jpg" };
                        String fileExtension = System.IO.Path.GetExtension(file.FileName);
                        string MainDirectory = string.Empty;
                        if (file.ContentType.Contains("image"))
                        {
                            if (SupportedImageFormat.Contains(fileExtension.ToLower()))
                            {
                                FilePath = string.Format("{0}{1}{2}", "/assets/images/Ground/img-Ground-", Guid.NewGuid().ToString(), fileExtension);


                                MainDirectory = Path.Combine(Server.MapPath("~" + FilePath));
                                file.SaveAs(MainDirectory);
                                ground.Picture= FilePath;
                            }
                            else
                            {
                                TempData["Error"] = "Wrong Format for Image";
                                return RedirectToAction("Index");
                            }
                        }
                        else
                        {
                            ground.Picture = "/assets/images/Ground/image.png";
                        }

                    }
                    
                }
                else
                {
                    ground.Picture = "/assets/images/Ground/image.png";
                }

                ground.IsActive = true;
                ground.IsDeleted = false;
                dbcontext.Grounds.Add(ground);
                dbcontext.SaveChanges();
                TempData["Message"] = "Grounds Created Successfully";
                return RedirectToAction("Index");


            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error Occured";
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = dbcontext.Grounds.Where(x => x.Id == Id).FirstOrDefault();
            var GroundType = dbcontext.GroundTypes.Where(x => x.IsDeleted == false).ToList();
            var dropdown = from type in GroundType
                           select new { value = type.id, text = type.GroundType1 };
            ViewBag.GroundType = dropdown;
            ViewBag.GroundImage = model.Picture;
            TempData["Id"] = Id;
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(DistrictPlayGroundManagementSystem.Ground ground)
        {
            try
            {
                DistrictPlayGroundManagementSystem.Ground _Ground = dbcontext.Grounds.Where(X => X.Id == ground.Id).FirstOrDefault();
                if (Request.Files.Count > 0)
                {
                    string FilePath = null;
                    var file = Request.Files[0];
                    if (file != null)
                    {
                        string[] SupportedImageFormat = { ".jpeg", ".png", ".jpg" };
                        String fileExtension = System.IO.Path.GetExtension(file.FileName);
                        
                        string MainDirectory = string.Empty;
                        if (file.ContentType.Contains("image"))
                        {
                            if (SupportedImageFormat.Contains(fileExtension.ToLower()))
                            {
                                FilePath = string.Format("{0}{1}{2}", "/assets/images/Ground/img-Ground-", Guid.NewGuid().ToString(), fileExtension);


                                MainDirectory = Path.Combine(Server.MapPath("~" + FilePath));
                                file.SaveAs(MainDirectory);
                                _Ground.Picture = FilePath;
                            }
                            else
                            {
                                TempData["Error"] = "Wrong Format for Image";
                                return RedirectToAction("Index");
                            }
                        }
                        else
                        {
                            ground.Picture = "/assets/images/Ground/image.png";
                        }

                    }
                }

                _Ground.Name = ground.Name;
                _Ground.GroundTypeID = ground.GroundTypeID;
                _Ground.Detail = ground.Detail;
                _Ground.Price = ground.Price;
                dbcontext.Entry(_Ground).State = System.Data.Entity.EntityState.Modified;
                dbcontext.SaveChanges();
                TempData["Message"] = "Ground Updated Successfully";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error Occured";
            }

            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            try
            {
                var ground = dbcontext.Grounds.Where(x => x.Id == id).FirstOrDefault();
                ground.IsDeleted = true;
                dbcontext.Entry(ground).State = EntityState.Modified;
                dbcontext.SaveChanges();
                TempData["Message"] = "Ground Deleted Successfully";

            }
            catch (Exception)
            {
                TempData["Error"] = "An error Occured";
            }
            return RedirectToAction("Index");
        }
        public ActionResult ActivateDeactivate(int id)
        {
            try
            {
                var ground = dbcontext.Grounds.Where(x => x.Id == id).FirstOrDefault();
                if (ground.IsActive == true)
                {
                    ground.IsActive = false;
                    TempData["Message"] = "Ground Deactivated  Successfully";
                }
                else
                {
                    ground.IsActive = true;
                    TempData["Message"] = "Ground Activated Successfully";
                }
                dbcontext.Entry(ground).State = EntityState.Modified;
                dbcontext.SaveChanges();

            }
            catch (Exception)
            {
                TempData["Error"] = "An error Occured";
            }
            return RedirectToAction("Index");
        }
    }
}

DistrictPlayGroundManagementSystem/Areas/Admin/Views/Ground/Create.cshtml
@model DistrictPlayGroundManagementSystem.Ground



@using (Html.BeginForm("Create", "Ground", FormMethod.Post, new { enctype = "multipart/form-data", id = "Areaform", area = "Admin" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 col-xs-12 text-center">
                        <h4>Ground</h4>
                        <small>Add Ground Here</small>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="alert alert-danger text-center" id="divMessage" style="display:none"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <div class="form-group">

                        <div class="change-avatar">
                            <div class="profile-img">
                                <img src="~/assets/images/Ground/images.png" id="image" alt="Ground Image">
                            </div>
                            <div class="upload-img">
                                <div class="change-photo-btn">
                                    <span><i class="fa fa-upload"></i> Upload Photo</span>
                                    <input type="file" name="Picture" id="Imageinput" class="upload">
                                </div>
                                <small class="form-text text-muted">Allowed JPG, GIF or PNG. Max size of 2MB</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                <div class="row">
                    <div class="col-md-6 col-xs-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, "Ground Name", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group mb-3">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Ground Name here ...", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-home"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.GroundType, "GroundType", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group mb-3">
                                @Html.DropDownListFor(model => model.GroundTypeID, new SelectList(ViewBag.GroundType, "value", "text"), new { @class = "form-control", required = "required" } )
                                @Html.ValidationMessageFor(model => model.GroundType, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-server"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Price, "Price", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group mb-2">
                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Price here ...", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-server"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Detail, "Detail", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group mb-2">
                                @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Detail here ...", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-server"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                <div class="row">
                    <div class="col-md-12  col-xs-12">
                        <button type="button" class="btn waves-effect waves-light btn-rounded btn btn-warning btn-sm float-left" data-dismiss="modal">
                            Close
                        </button>
                        <button type="submit" class="btn waves-effect waves-light btn-rounded btn btn-primary btn-sm float-right">
                            Add
                        </button>
                    </div>
                </div>
            </div>
        </div>
  
}
<script>
     function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]); 
        }
    }
  

    $("#Imageinput").change(function () {
        readURL(this);
    });
</script>

DistrictPlayGroundManagementSystem/Areas/Admin/Views/Ground/Edit.cshtml
@model DistrictPlayGroundManagementSystem.Ground

@using (Html.BeginForm("Edit", "Ground", FormMethod.Post, new { enctype = "multipart/form-data", id = "Areaform", area = "Admin" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 col-xs-12 text-center">
                        <h4>Ground</h4>
                        <small>Update Ground Here</small>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="alert alert-danger text-center" id="divMessage" style="display:none"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">

                        <div class="change-avatar">
                            <div class="profile-img">
                                <img src="@ViewBag.GroundImage" id="image" alt="Ground Image">
                            </div>
                            <div class="upload-img">
                                <div class="change-photo-btn">
                                    <span><i class="fa fa-upload"></i> Upload Photo</span>
                                    <input type="file" name="Picture" id="Imageinput" class="upload">
                                </div>
                                <small class="form-text text-muted">Allowed JPG, GIF or PNG. Max size of 2MB</small>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-xs-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, "Ground Name", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group mb-3">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Ground Name here ...", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-home"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.GroundType, "GroundType", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group mb-2">
                                @Html.DropDownListFor(model => model.GroundTypeID, new SelectList(ViewBag.GroundType, "value", "text"), new { @class = "form-control", placeholder = "Enter Email here ...", required = "required"  })
                                @Html.ValidationMessageFor(model => model.GroundType, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-server"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Price, "Price", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group mb-2">
                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Price here ...", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-server"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Detail, "Detail", htmlAttributes: new { @class = "control-label" })
                            <div class="input-group mb-2">
                                @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Detail here ...", required = "required" } })
                                @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-server"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                <div class="row">
                    <div class="col-md-12  col-xs-12">
                        <button type="button" class="btn waves-effect waves-light btn-rounded btn btn-warning btn-sm float-left" data-dismiss="modal">
                            Close
                        </button>
                        <button type="submit" class="btn waves-effect waves-light btn-rounded btn btn-primary btn-sm float-right">
                            Update
                        </button>
                    </div>
                </div>
            </div>
        </div>
    
        }
        
<script>
     function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }


    $("#Imageinput").change(function () {
        readURL(this);
    });
</script>

DistrictPlayGroundManagementSystem/Areas/Admin/Views/Ground/Index.cshtml
@model IEnumerable<DistrictPlayGroundManagementSystem.Ground>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
    <style>
        .change-photo-btn {
            background-color: #1e88e5;
            border-radius: 50px;
            color: #fff;
            cursor: pointer;
            display: block;
            font-size: 13px;
            font-weight: 600;
            margin: 0 auto;
            padding: 10px 15px;
            position: relative;
            transition: .3s;
            text-align: center;
            width: 220px;
        }

            .change-photo-btn input.upload {
                bottom: 0;
                cursor: pointer;
                filter: alpha(opacity=0);
                left: 0;
                margin: 0;
                opacity: 0;
                padding: 0;
                position: absolute;
                right: 0;
                top: 0;
                width: 220px;
            }
    </style>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-xs-12 mb-1">
                    <h3 class="content-header-title"> Ground List</h3>
                </div>

                <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
                    <div class="breadcrumb-wrapper col-xs-12">
                        <button type="button" class="btn waves-effect waves-light btn-rounded  btn btn-success btn-sm" onclick="OpenModelPopup(this)" data="/Admin/Ground/Create/">Create</button>



                    </div>
                </div>
            </div>

            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayName("GroundType1")
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Picture)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Detail)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Price)
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GroundType.GroundType1)
                                </td>
                                <td>
                                   <img src="@item.Picture"  style="border-radius:0px;width:auto;height:70px"/>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Detail)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                @if (item.IsActive == true)
                                {
                                    <td>
                                        <a class="btn btn-danger btn-rounded btn-fw" href="/Admin/Ground/ActivateDeactivate?id=@item.Id">Deactivate</a>

                                    </td>
                                }
                                else
                                {
                                    <td>
                                        <a class="btn btn-primary btn-rounded btn-fw" href="/Admin/Ground/ActivateDeactivate?id=@item.Id">Activate</a>

                                    </td>
                                }
                                <td>
                                    <button type="button" class="btn waves-effect waves-light btn-rounded  btn btn-primary " onclick="OpenModelPopup(this)" data="/Admin/Ground/Edit?Id=@item.Id">Edit</button>
                                    <a class="btn btn-danger btn-rounded btn-fw" id="deletebtn" onclick="JSalert()" href="/Admin/Ground/Delete?id=@item.Id">Delete</a>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='myModalContent'>
            </div>
        </div>
    </div>
</div>


@if (ViewBag.Message != null && ViewBag.Message != "")
{
    <script>
             toastr.success('@ViewBag.Message');
    </script>
}
@if (ViewBag.Error != null && ViewBag.Error != "")
{
    <script>
               toastr.error('@ViewBag.Error');
    </script>
}


<script>
        function JSalert() {
        event.preventDefault();  
        Swal.fire({
            title: 'Are you sure you want to delete this Ground?',
            showDenyButton: true,
            showCancelButton: true,
            confirmButtonText: `Delete`,
            denyButtonText: `Don't Delete`,
        }).then((result) => {
            if (result.isConfirmed) {
                fetch($('#deletebtn').prop('href')).then(() => {
 
                    Swal.fire(
                        'Deleted!',
                        'Your Ground has been deleted.',
                        'success'
                    ).then(function() {
    location.reload()
});
                    
                })
            }
            else {
                return false
            }
        })
           
}
</script>