DistrictPlayGroundManagementSystem/Areas/Admin/Controllers/FeedBackController.cs
using DistrictPlayGroundManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistrictPlayGroundManagementSystem.Areas.Admin.Controllers
{
    [AuthorizeAdmin]
    public class FeedBackController : Controller
    {
        public DistrictPlayGroundManagmentEntities dbcontext = new DistrictPlayGroundManagmentEntities();
        // GET: Admin/FeedBack
        public ActionResult Index()
        {
            var list = dbcontext.Feedbacks.ToList();
            return View(list);
        }
    }
}

DistrictPlayGroundManagementSystem/Areas/User/Controllers/FeedBackController.cs
using DistrictPlayGroundManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistrictPlayGroundManagementSystem.Areas.User.Controllers
{
    [AuthorizeUser]
    public class FeedBackController : Controller
    {
        
        // GET: User/FeedBack
        public DistrictPlayGroundManagmentEntities dbcontext = new DistrictPlayGroundManagmentEntities();
        public ActionResult Index()
        {
            ViewBag.Message = TempData["Message"];
            ViewBag.Error = TempData["Error"];
            int UserId = (int)Session["UserId"];
            var list = dbcontext.Feedbacks.Where(X =>  X.Userid == UserId).ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var Ground = dbcontext.Grounds.Where(x => x.IsDeleted == false).ToList();
            var Grounddropdown = from type in Ground
                                 select new { value = type.Id, text = type.Name };
            ViewBag.Ground = Grounddropdown;
            int UserId = (int)Session["UserId"];
            var User = dbcontext.Users.Where(x => x.IsDeleted == false && x.Id == UserId).ToList();
            var Userdropdown = from type in User
                               select new { value = type.Id, text = type.Name };
            ViewBag.User = Userdropdown;
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(DistrictPlayGroundManagementSystem.Feedback feedback)
        {
            try
            {


                dbcontext.Feedbacks.Add(feedback);
                dbcontext.SaveChanges();
                TempData["Message"] = "Feedback Created Successfully";
                return RedirectToAction("Index");


            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error Occured";
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = dbcontext.Feedbacks.Where(x => x.id == Id).FirstOrDefault();
            var Ground = dbcontext.Grounds.Where(x => x.IsDeleted == false).ToList();
            var Grounddropdown = from type in Ground
                                 select new { value = type.Id, text = type.Name };
            ViewBag.Ground = Grounddropdown;
            int UserId = (int)Session["UserId"];
            var User = dbcontext.Users.Where(x => x.IsDeleted == false && x.Id == UserId).ToList();
            var Userdropdown = from type in User
                               select new { value = type.Id, text = type.Name };
            ViewBag.User = Userdropdown;
           
            TempData["Id"] = Id;
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(DistrictPlayGroundManagementSystem.Feedback feedback)
        {
            try
            {
                DistrictPlayGroundManagementSystem.Feedback _Feedback = dbcontext.Feedbacks.Where(X => X.id == feedback.id).FirstOrDefault();
                _Feedback.Details = feedback.Details;
                _Feedback.Groundid = feedback.Groundid;
                _Feedback.Userid = feedback.Userid;
                dbcontext.Entry(_Feedback).State = System.Data.Entity.EntityState.Modified;
                dbcontext.SaveChanges();
                TempData["Message"] = "Feedback Updated Successfully";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error Occured";
            }

            return RedirectToAction("Index");
        }
       

    }
}

DistrictPlayGroundManagementSystem/Areas/User/Views/FeedBack/Create.cshtml
@model DistrictPlayGroundManagementSystem.Feedback

@using (Html.BeginForm("Create", "FeedBack", FormMethod.Post, new { enctype = "multipart/form-data", id = "Areaform", area = "User" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 col-xs-12 text-center">
                        <h4>FeedBack</h4>
                        <small>Add FeedBack Here</small>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="alert alert-danger text-center" id="divMessage" style="display:none"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">

            <div class="col-md-6 col-sm-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.Groundid, "Groundid", htmlAttributes: new { @class = "control-label" })
                    <div class="input-group mb-2">
                        @Html.DropDownListFor(model => model.Groundid, new SelectList(ViewBag.Ground, "value", "text"), new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Email here ...", required = "required" } })
                        @Html.ValidationMessageFor(model => model.Groundid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-server"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.Userid, "Userid", htmlAttributes: new { @class = "control-label" })
                    <div class="input-group mb-2">
                        @Html.DropDownListFor(model => model.Userid, new SelectList(ViewBag.User, "value", "text"), new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Email here ...", required = "required" } })
                        @Html.ValidationMessageFor(model => model.Userid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-server"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Details, "Details", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Details here ...", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class="row">
                <div class="col-md-12  col-xs-12">
                    <button type="button" class="btn waves-effect waves-light btn-rounded btn btn-warning btn-sm float-left" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn waves-effect waves-light btn-rounded btn btn-primary btn-sm float-right">
                        Add
                    </button>
                </div>
            </div>
        </div>
    </div>
}

DistrictPlayGroundManagementSystem/Areas/User/Views/FeedBack/Edit.cshtml
@model DistrictPlayGroundManagementSystem.Feedback

@using (Html.BeginForm("Edit", "FeedBack", FormMethod.Post, new { enctype = "multipart/form-data", id = "Areaform", area = "User" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 col-xs-12 text-center">
                        <h4>FeedBack</h4>
                        <small>Update FeedBack Here</small>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="alert alert-danger text-center" id="divMessage" style="display:none"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                @Html.HiddenFor(model=>model.id)
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Groundid, "Groundid", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.DropDownListFor(model => model.Groundid, new SelectList(ViewBag.Ground, "value", "text"), new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Email here ...", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Groundid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Userid, "Userid", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.DropDownListFor(model => model.Userid, new SelectList(ViewBag.User, "value", "text"), new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Email here ...", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Userid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Details, "Details", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Details here ...", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class="row">
                <div class="col-md-12  col-xs-12">
                    <button type="button" class="btn waves-effect waves-light btn-rounded btn btn-warning btn-sm float-left" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn waves-effect waves-light btn-rounded btn btn-primary btn-sm float-right">
                        Update
                    </button>
                </div>
            </div>
        </div>
    </div>
}

DistrictPlayGroundManagementSystem/Areas/User/Views/FeedBack/Index.cshtml
@model IEnumerable<DistrictPlayGroundManagementSystem.Feedback>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-xs-12 mb-1">
                    <h3 class="content-header-title"> FeedBack List</h3>
                </div>

                <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
                    <div class="breadcrumb-wrapper col-xs-12">
                        <button type="button" class="btn waves-effect waves-light btn-rounded  btn btn-success btn-sm" onclick="OpenModelPopup(this)" data="/User/FeedBack/Create/">Create</button>



                    </div>
                </div>
            </div>

            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Ground.Name)
                            </th>
                           
                            <th>
                                @Html.DisplayNameFor(model => model.User.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Details)
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ground.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.User.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Details)
                                </td>
                                <td>
                                    <button type="button" class="btn waves-effect waves-light btn-rounded  btn btn-primary " onclick="OpenModelPopup(this)" data="/User/FeedBack/Edit?Id=@item.id">Edit</button>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='myModalContent'>
            </div>
        </div>
    </div>
</div>


@if (ViewBag.Message != null && ViewBag.Message != "")
{
    <script>
             toastr.success('@ViewBag.Message');
    </script>
}
@if (ViewBag.Error != null && ViewBag.Error != "")
{
    <script>
               toastr.error('@ViewBag.Error');
    </script>
}

<script>
    function JSalert() {
        event.preventDefault();
        Swal.fire({
            title: 'Are you sure you want to delete this FeedBack?',
            showDenyButton: true,
            showCancelButton: true,
            confirmButtonText: `Delete`,
            denyButtonText: `Don't Delete`,
        }).then((result) => {
            if (result.isConfirmed) {
                fetch($('#deletebtn').prop('href')).then(() => {

                    Swal.fire(
                        'Deleted!',
                        'Your FeedBack has been deleted.',
                        'success'
                    ).then(function () {
                        location.reload()
                    });

                })
            }
            else {
                return false
            }
        })

    }

</script>