DistrictPlayGroundManagementSystem/Areas/Admin/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DistrictPlayGroundManagementSystem.Models;

namespace DistrictPlayGroundManagementSystem.Areas.Admin.Controllers
{
    [AuthorizeAdmin]
    public class BookingController : Controller
    {
        // GET: Admin/Booking
        public DistrictPlayGroundManagmentEntities dbcontext = new DistrictPlayGroundManagmentEntities();
   
        public ActionResult Index()
        {
            ViewBag.Message = TempData["Message"];
            ViewBag.Error = TempData["Error"];
            var list = dbcontext.Bookings.Where(X => X.IsDeleted == false).ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var Team = dbcontext.Teams.Where(x => x.IsDeleted == false).ToList();
            var dropdown = from type in Team
                           select new { value = type.id, text = type.Name };
            ViewBag.Team = dropdown;
            var Ground = dbcontext.Grounds.Where(x => x.IsDeleted == false).ToList();
            var Grounddropdown = from type in Ground
                           select new { value = type.Id, text = type.Name};
            ViewBag.Ground = Grounddropdown;
            var User = dbcontext.Users.Where(x => x.IsDeleted == false).ToList();
            var Userdropdown = from type in User
                               select new { value = type.Id, text = type.Name};
            ViewBag.User = Userdropdown;
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(DistrictPlayGroundManagementSystem.Booking booking)
        {
            try
            {


                booking.IsDeleted = false;
                booking.IsAuthorized= false;
                booking.Date = booking.Date.Replace("T", " ");
                dbcontext.Bookings.Add(booking);
                dbcontext.SaveChanges();
                TempData["Message"] = "Booking Created Successfully";
                return RedirectToAction("Index");


            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error Occured";
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = dbcontext.Bookings.Where(x => x.id == Id).FirstOrDefault();
            var Team = dbcontext.Teams.Where(x => x.IsDeleted == false).ToList();
            var dropdown = from type in Team
                           select new { value = type.id, text = type.Name };
            ViewBag.Team = dropdown;
            var Ground = dbcontext.Grounds.Where(x => x.IsDeleted == false).ToList();
            var Grounddropdown = from type in Ground
                                 select new { value = type.Id, text = type.Name };
            ViewBag.Ground = Grounddropdown;
            var User = dbcontext.Users.Where(x => x.IsDeleted == false).ToList();
            var Userdropdown = from type in User
                               select new { value = type.Id, text = type.Name };
            ViewBag.User = Userdropdown;
            model.Date = (String.Format("{0:yyyy-MM-dd}", model.Date));
            TempData["Id"] = Id;
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(DistrictPlayGroundManagementSystem.Booking booking)
        {
            try
            {
                DistrictPlayGroundManagementSystem.Booking _booking = dbcontext.Bookings.Where(X => X.id == booking.id).FirstOrDefault();
                _booking.Date = booking.Date.Replace("T", " ");
                _booking.Teamid= booking.Teamid;
                _booking.Groundid = booking.Groundid;
                _booking.Userid = booking.Userid;
                _booking.Detail = booking.Detail;
                dbcontext.Entry(_booking).State = System.Data.Entity.EntityState.Modified;
                dbcontext.SaveChanges();
                TempData["Message"] = "Booking Updated Successfully";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error Occured";
            }

            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            try
            {
                var booking = dbcontext.Bookings.Where(x => x.id == id).FirstOrDefault();
                booking.IsDeleted = true;
                dbcontext.Entry(booking).State = EntityState.Modified;
                dbcontext.SaveChanges();
                TempData["Message"] = "Booking Deleted Successfully";

            }
            catch (Exception)
            {
                TempData["Error"] = "An error Occured";
            }
            return RedirectToAction("Index");
        }
        public ActionResult Authorized(int id,string concession)
        {
            bool success = false;
            try
            {

                var booking = dbcontext.Bookings.Where(x => x.id == id).FirstOrDefault();
            if (booking != null)
            {
                    decimal totalamount = 0;
                if (concession != "" && concession != "0")
                {
                    decimal conc = Convert.ToDecimal(concession);
                    decimal price = Convert.ToDecimal(booking.Ground.Price);
                    decimal total = (conc / 100) * price;
                    totalamount = Convert.ToDecimal(price - total);
                     
                }
                else
                {
                    totalamount = Convert.ToDecimal(booking.Ground.Price);
                    concession = "0";
                }
                Account account = new Account();
                account.Date =  Convert.ToDateTime(booking.Date);
                account.Bookingid = booking.id;
                account.concession = Convert.ToInt32(concession);
                account.Amount = totalamount;
                dbcontext.Accounts.Add(account);
                dbcontext.SaveChanges();
              
                    booking.IsAuthorized = true;
                    TempData["Message"] = "Booking  Authorized Successfully";
            }
                dbcontext.Entry(booking).State = EntityState.Modified;
                dbcontext.SaveChanges();
                success = true;
            }
            catch (Exception)
            {
                TempData["Error"] = "An error Occured";
                success = false;
            }
            return Json(new { success = success });
        }
    }
}

DistrictPlayGroundManagementSystem/Areas/User/Controllers/BookingController.cs
using DistrictPlayGroundManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistrictPlayGroundManagementSystem.Areas.User.Controllers
{
    [AuthorizeUser]
    public class BookingController : Controller
    {
        // GET: User/Booking
        public DistrictPlayGroundManagmentEntities dbcontext = new DistrictPlayGroundManagmentEntities();

        public ActionResult Index()
        {
            ViewBag.Message = TempData["Message"];
            ViewBag.Error = TempData["Error"];
            int UserId = (int)Session["UserId"];
            var list = dbcontext.Bookings.Where(X => X.IsDeleted == false && X.Userid == UserId).ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var Team = dbcontext.Teams.Where(x => x.IsDeleted == false).ToList();
            var dropdown = from type in Team
                           select new { value = type.id, text = type.Name };
            ViewBag.Team = dropdown;
            var Ground = dbcontext.Grounds.Where(x => x.IsDeleted == false).ToList();
            var Grounddropdown = from type in Ground
                                 select new { value = type.Id, text = type.Name };
            ViewBag.Ground = Grounddropdown;
            int UserId = (int)Session["UserId"];
            var User = dbcontext.Users.Where(x => x.IsDeleted == false && x.Id == UserId).ToList();
            var Userdropdown = from type in User
                               select new { value = type.Id, text = type.Name };
            ViewBag.User = Userdropdown;
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(DistrictPlayGroundManagementSystem.Booking booking)
        {
            try
            {


                booking.IsDeleted = false;
                booking.IsAuthorized = false;
                dbcontext.Bookings.Add(booking);
                dbcontext.SaveChanges();
                TempData["Message"] = "Booking Created Successfully";
                return RedirectToAction("Index");


            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error Occured";
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = dbcontext.Bookings.Where(x => x.id == Id).FirstOrDefault();
            var Team = dbcontext.Teams.Where(x => x.IsDeleted == false).ToList();
            var dropdown = from type in Team
                           select new { value = type.id, text = type.Name };
            ViewBag.Team = dropdown;
            var Ground = dbcontext.Grounds.Where(x => x.IsDeleted == false).ToList();
            var Grounddropdown = from type in Ground
                                 select new { value = type.Id, text = type.Name };
            ViewBag.Ground = Grounddropdown;
            int UserId = (int)Session["UserId"];
            var User = dbcontext.Users.Where(x => x.IsDeleted == false && x.Id == UserId).ToList();
            var Userdropdown = from type in User
                               select new { value = type.Id, text = type.Name };
            ViewBag.User = Userdropdown;
            model.Date = (String.Format("{0:s}", model.Date));
            TempData["Id"] = Id;
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(DistrictPlayGroundManagementSystem.Booking booking)
        {
            try
            {
                DistrictPlayGroundManagementSystem.Booking _booking = dbcontext.Bookings.Where(X => X.id == booking.id).FirstOrDefault();
                _booking.Date = booking.Date;
                _booking.Teamid = booking.Teamid;
                _booking.Groundid = booking.Groundid;
                _booking.Userid = booking.Userid;
                _booking.Detail = booking.Detail;
                dbcontext.Entry(_booking).State = System.Data.Entity.EntityState.Modified;
                dbcontext.SaveChanges();
                TempData["Message"] = "Booking Updated Successfully";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error Occured";
            }

            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            try
            {
                var booking = dbcontext.Bookings.Where(x => x.id == id).FirstOrDefault();
                booking.IsDeleted = true;
                dbcontext.Entry(booking).State = EntityState.Modified;
                dbcontext.SaveChanges();
                TempData["Message"] = "Booking Deleted Successfully";

            }
            catch (Exception)
            {
                TempData["Error"] = "An error Occured";
            }
            return RedirectToAction("Index");
        }
   
    }
}

DistrictPlayGroundManagementSystem/Areas/Admin/Views/Booking/Create.cshtml
@model DistrictPlayGroundManagementSystem.Booking

@using (Html.BeginForm("Create", "Booking", FormMethod.Post, new { enctype = "multipart/form-data", id = "Areaform", area = "Admin" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 col-xs-12 text-center">
                        <h4>Booking</h4>
                        <small>Add Booking Here</small>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="alert alert-danger text-center" id="divMessage" style="display:none"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Userid, "Userid", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.DropDownListFor(model => model.Userid, new SelectList(ViewBag.User, "value", "text"), new { @class = "form-control",  required = "required" })
                            @Html.ValidationMessageFor(model => model.Userid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Teamid, "Teamid", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.DropDownListFor(model => model.Teamid, new SelectList(ViewBag.Team, "value", "text"),  new { @class = "form-control",required = "required" } )
                            @Html.ValidationMessageFor(model => model.Teamid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Groundid, "Groundid", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.DropDownListFor(model => model.Groundid, new SelectList(ViewBag.Ground, "value", "text"),new { @class = "form-control", required = "required" } )
                            @Html.ValidationMessageFor(model => model.Groundid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Date, "Date", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" ,type="datetime-local", placeholder = "Enter Detail here ...", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Detail, "Detail", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Detail here ...", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class="row">
                <div class="col-md-12  col-xs-12">
                    <button type="button" class="btn waves-effect waves-light btn-rounded btn btn-warning btn-sm float-left" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn waves-effect waves-light btn-rounded btn btn-primary btn-sm float-right">
                        Add
                    </button>
                </div>
            </div>
        </div>
    </div>
}
<script>

</script>

DistrictPlayGroundManagementSystem/Areas/Admin/Views/Booking/Edit.cshtml
@model DistrictPlayGroundManagementSystem.Booking

@using (Html.BeginForm("Edit", "Booking", FormMethod.Post, new { enctype = "multipart/form-data", id = "Areaform", area = "Admin" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 col-xs-12 text-center">
                        <h4>Booking</h4>
                        <small>Update Booking Here</small>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="alert alert-danger text-center" id="divMessage" style="display:none"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    @Html.HiddenFor(model => model.id)
                    <div class="form-group">
                        @Html.LabelFor(model => model.Userid, "Userid", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.DropDownListFor(model => model.Userid, new SelectList(ViewBag.User, "value", "text"), new { @class = "form-control", required = "required"  })
                            @Html.ValidationMessageFor(model => model.Userid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Teamid, "Teamid", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.DropDownListFor(model => model.Teamid, new SelectList(ViewBag.Team, "value", "text"),  new { @class = "form-control", required = "required"  })
                            @Html.ValidationMessageFor(model => model.Teamid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Groundid, "Groundid", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.DropDownListFor(model => model.Groundid, new SelectList(ViewBag.Ground, "value", "text"),new { @class = "form-control", required = "required" })
                            @Html.ValidationMessageFor(model => model.Groundid, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Date, "Date", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", type = "datetime-local", placeholder = "Enter Detail here ...", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Detail, "Detail", htmlAttributes: new { @class = "control-label" })
                        <div class="input-group mb-2">
                            @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Detail here ...", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })<div class="input-group-append"></div>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-server"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class="row">
                <div class="col-md-12  col-xs-12">
                    <button type="button" class="btn waves-effect waves-light btn-rounded btn btn-warning btn-sm float-left" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn waves-effect waves-light btn-rounded btn btn-primary btn-sm float-right">
                        Update
                    </button>
                </div>
            </div>
        </div>
    </div>
}